export type ConfigurationKey =
	| 'defaultWorkspaceId'
	| 'fetchLimit'
	| 'hideSensitiveData'
	| 'showIds'
	| 'workspaces.showNumberOfMembers'
	| 'tracking.workspaceId'
	| 'tracking.projectId'
	| 'tracking.taskId'
	| 'tracking.billable'
	| 'tracking.autostart'
	| 'tracking.autostop'
	| 'pomodoro.enabled'
	| 'pomodoro.focusMinutes'
	| 'pomodoro.shortBreakMinutes'
	| 'pomodoro.longBreakMinutes'
	| 'pomodoro.sessionsBeforeLongBreak'
	| 'pomodoro.automaticBreaks';
